FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache curl netcat-openbsd

COPY src/backend/package*.json ./
RUN npm install

COPY src/backend/ ./

RUN chmod +x entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["sh", "entrypoint.sh"]